name: finance-insure-care
services:
  database:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: FIC-Database
    ports:
      - "${DATABASE_PORT}:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DATABASE_PASSWORD}